# Generated by Django 4.1.5 on 2023-03-09 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prenom', models.CharField(max_length=200)),
                ('nom', models.CharField(max_length=200)),
                ('filiere', models.CharField(choices=[('GEA', 'GEA'), ('GACT', 'GACT'), ('BTP', 'BTP'), ('GT', 'GT'), ('GEII', 'GEII'), ('GLT', 'GLT'), ('LPGT', 'LPGT')], max_length=4)),
                ('token', models.CharField(max_length=300)),
                ('is_scanned', models.BooleanField(default=False)),
            ],
        ),
    ]
